"""sync current models

Revision ID: cd8885062f2e
Revises: d98129e410a1
Create Date: 2026-09-03 22:48:52.780065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd8885062f2e'
down_revision: Union[str, None] = 'd98129e410a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###

    op.create_table(
        'challenges',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('capability_id', sa.UUID(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('difficulty', sa.String(length=50), nullable=False),
        sa.Column('time_limit_minutes', sa.Integer(), nullable=True),
        sa.Column(
            'evaluation_criteria',
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()),
                'postgresql'
            ),
            nullable=True
        ),
        sa.Column('starter_content', sa.Text(), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False
        ),
        sa.ForeignKeyConstraint(
            ['capability_id'],
            ['capabilities.id'],
            ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(
        op.f('ix_challenges_capability_id'),
        'challenges',
        ['capability_id'],
        unique=False
    )

    op.create_table(
        'oral_assessments',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('capability_id', sa.UUID(), nullable=False),
        sa.Column('question', sa.Text(), nullable=False),
        sa.Column('difficulty', sa.String(length=50), nullable=False),
        sa.Column('audio_url', sa.String(length=500), nullable=True),
        sa.Column('transcript', sa.Text(), nullable=True),
        sa.Column('correctness_score', sa.Float(), nullable=False),
        sa.Column('relevance_score', sa.Float(), nullable=False),
        sa.Column('depth_score', sa.Float(), nullable=False),
        sa.Column('clarity_score', sa.Float(), nullable=False),
        sa.Column('overall_score', sa.Float(), nullable=False),
        sa.Column('feedback', sa.Text(), nullable=True),
        sa.Column(
            'status',
            sa.Enum(
                'CREATED',
                'PROCESSING',
                'COMPLETED',
                'FAILED',
                name='oral_assessment_status'
            ),
            nullable=False
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False
        ),
        sa.Column(
            'completed_at',
            sa.DateTime(timezone=True),
            nullable=True
        ),
        sa.ForeignKeyConstraint(
            ['capability_id'],
            ['capabilities.id'],
            ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
            ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(
        op.f('ix_oral_assessments_capability_id'),
        'oral_assessments',
        ['capability_id'],
        unique=False
    )

    op.create_index(
        op.f('ix_oral_assessments_user_id'),
        'oral_assessments',
        ['user_id'],
        unique=False
    )

    op.create_table(
        'challenge_submissions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('challenge_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('submission_text', sa.Text(), nullable=True),
        sa.Column('code', sa.Text(), nullable=True),
        sa.Column('repository_url', sa.String(length=500), nullable=True),
        sa.Column('test_score', sa.Float(), nullable=True),
        sa.Column('ai_score', sa.Float(), nullable=True),
        sa.Column('final_score', sa.Float(), nullable=True),
        sa.Column('feedback', sa.Text(), nullable=True),
        sa.Column(
            'status',
            sa.Enum(
                'SUBMITTED',
                'EVALUATING',
                'COMPLETED',
                'FAILED',
                name='challenge_submission_status'
            ),
            nullable=False
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False
        ),
        sa.Column(
            'evaluated_at',
            sa.DateTime(timezone=True),
            nullable=True
        ),
        sa.ForeignKeyConstraint(
            ['challenge_id'],
            ['challenges.id'],
            ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
            ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(
        op.f('ix_challenge_submissions_challenge_id'),
        'challenge_submissions',
        ['challenge_id'],
        unique=False
    )

    op.create_index(
        op.f('ix_challenge_submissions_user_id'),
        'challenge_submissions',
        ['user_id'],
        unique=False
    )

    op.add_column(
        'evidence',
        sa.Column('source_id', sa.UUID(), nullable=True)
    )

    op.add_column(
        'evidence',
        sa.Column(
            'score',
            sa.Float(),
            nullable=False,
            server_default=sa.text('0')
        )
    )

    op.add_column(
        'evidence',
        sa.Column(
            'quality',
            sa.Float(),
            nullable=False,
            server_default=sa.text('0')
        )
    )

    verification_status_enum = postgresql.ENUM(
        'PENDING',
        'VERIFIED',
        'REJECTED',
        name='verification_status',
        create_type=False
    )

    verification_status_enum.create(
        op.get_bind(),
        checkfirst=True
    )

    op.add_column(
        'evidence',
        sa.Column(
            'verification_status',
            verification_status_enum,
            nullable=False,
            server_default='PENDING'
        )
    )

    op.add_column(
        'evidence',
        sa.Column(
            'evidence_metadata',
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()),
                'postgresql'
            ),
            nullable=True
        )
    )

    op.add_column(
        'evidence',
        sa.Column(
            'expires_at',
            sa.DateTime(timezone=True),
            nullable=True
        )
    )

    op.create_index(
        op.f('ix_evidence_capability_id'),
        'evidence',
        ['capability_id'],
        unique=False
    )

    op.create_index(
        op.f('ix_evidence_user_id'),
        'evidence',
        ['user_id'],
        unique=False
    )

    op.drop_constraint(
        'problem_analyses_problem_id_key',
        'problem_analyses',
        type_='unique'
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###

    op.create_unique_constraint(
        'problem_analyses_problem_id_key',
        'problem_analyses',
        ['problem_id']
    )

    op.drop_index(
        op.f('ix_evidence_user_id'),
        table_name='evidence'
    )

    op.drop_index(
        op.f('ix_evidence_capability_id'),
        table_name='evidence'
    )

    op.drop_column('evidence', 'expires_at')
    op.drop_column('evidence', 'evidence_metadata')
    op.drop_column('evidence', 'verification_status')

    verification_status_enum = postgresql.ENUM(
        'PENDING',
        'VERIFIED',
        'REJECTED',
        name='verification_status',
        create_type=False
    )

    verification_status_enum.drop(
        op.get_bind(),
        checkfirst=True
    )

    op.drop_column('evidence', 'quality')
    op.drop_column('evidence', 'score')
    op.drop_column('evidence', 'source_id')

    op.drop_index(
        op.f('ix_challenge_submissions_user_id'),
        table_name='challenge_submissions'
    )

    op.drop_index(
        op.f('ix_challenge_submissions_challenge_id'),
        table_name='challenge_submissions'
    )

    op.drop_table('challenge_submissions')

    op.drop_index(
        op.f('ix_oral_assessments_user_id'),
        table_name='oral_assessments'
    )

    op.drop_index(
        op.f('ix_oral_assessments_capability_id'),
        table_name='oral_assessments'
    )

    op.drop_table('oral_assessments')

    op.drop_index(
        op.f('ix_challenges_capability_id'),
        table_name='challenges'
    )

    op.drop_table('challenges')

    # ### end Alembic commands ###